---
name: Bump Packio version
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: "github.event_name == 'pull_request'"
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C++ project and run C++ tests
        run: |
          mkdir build && cd build
          cmake -DOPENFDCM_BUILD_TESTS=ON .. && cmake --build .
          ctest .
          cd ..

  bump_version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}
      - id: cz
        name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ github.token }}
      - name: Print Version
        run: echo "Bumped to version ${{ steps.cz.outputs.version }}"