---
name: Bump Packio version
on:
  pull_request:
    branches:
      - master

jobs:
  test-packio:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build C++ project and run C++ tests
        run: |
          mkdir build && cd build
          cmake -DPACKIO_BUILD_TESTS=ON .. && cmake --build .
          ctest .
          cd ..